#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\CommandLoader\ContainerCommandLoader;
use Yiisoft\Composer\Config\Builder;
use Yiisoft\Di\Container;

$autoload = __DIR__ . '/vendor/autoload.php';

if (!is_file($autoload)) {
    die('You need to set up the project dependencies using Composer');
}

require_once $autoload;

$console = 'console';
$providers = 'providers';

if (getenv('Alternatives') !== false) {
    $console = getenv('Alternatives') . '/console';
    $providers = getenv('Alternatives') . '/providers';
}

$container = new Container(
    require Builder::path($console),
    require Builder::path($providers),
);

$params = require Builder::path('params');

$loader = new ContainerCommandLoader(
    $container,
    $params['yiisoft/yii-console']['commands']
);


$app = new Application();

$app->setCommandLoader($loader);

$app->run();

